export const products = [
  {
    id: 1,
    logo: "logo-red-dragon.jpg",
    title: "IPS LCD Gaming Monitor",
    img: "monitor.png",
    off: 5,
    price: 450,
    oldPrice: 560,
    rate: 91,
    cant: 1,
  },
  {
    id: 2,
    logo: "logo-jbl.jpg",
    title: "Baffle JBL",
    img: "parlante-jbl.png",
    off: 5,
    price: 650,
    oldPrice: 740,
    rate: 95,
    cant: 1,
  },
  {
    id: 3,
    logo: "logo-apple.jpg",
    title: "iPhone 14 Series",
    img: "iphone.png",
    off: 10,
    price: 1500,
    oldPrice: 1800,
    rate: 98,
    cant: 1,
  },
  {
    id: 4,
    logo: "logo-control.png",
    title: "HAVIT HV-G92 Gamepad",
    img: "control.png",
    off: 40,
    price: 120,
    oldPrice: 160,
    rate: 88,
    cant: 1,
  },
  {
    id: 5,
    logo: "logo-red-dragon.jpg",
    title: "IPS LCD Gaming Monitor",
    img: "monitor.png",
    off: 5,
    price: 450,
    oldPrice: 560,
    rate: 91,
    cant: 1,
  },
];
